# Generated by Django 4.2.29 on 2026-03-24 07:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('credit', models.PositiveSmallIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('roll_number', models.CharField(max_length=50, unique=True)),
                ('department', models.CharField(max_length=255)),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('enrollment_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['roll_number'], name='api_student_roll_nu_f8ee59_idx'), models.Index(fields=['department'], name='api_student_departm_6c2e95_idx'), models.Index(fields=['status'], name='api_student_status_8ed2d4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('total_marks', models.FloatField(default=100.0)),
                ('percentage', models.FloatField(default=0.0, editable=False)),
                ('grade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], editable=False, max_length=2)),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], editable=False, max_length=4)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.subject')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student'], name='api_result_student_fbd2a5_idx'), models.Index(fields=['subject'], name='api_result_subject_98b495_idx'), models.Index(fields=['exam_date'], name='api_result_exam_da_d61fed_idx')],
                'unique_together': {('student', 'subject', 'exam_date')},
            },
        ),
    ]
