# Generated by Django 6.0.3 on 2026-03-25 17:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('subject_code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('credit', models.PositiveIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('roll_number', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('department', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['roll_number'], name='api_student_roll_nu_f8ee59_idx'), models.Index(fields=['department'], name='api_student_departm_6c2e95_idx'), models.Index(fields=['status'], name='api_student_status_8ed2d4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('total_marks', models.FloatField(default=100)),
                ('percentage', models.FloatField(default=0, editable=False)),
                ('grade', models.CharField(choices=[('O', 'Outstanding (90-100)'), ('A+', 'Excellent (80-89)'), ('A', 'Very Good (70-79)'), ('B+', 'Good (60-69)'), ('B', 'Above Average (50-59)'), ('C', 'Average (40-49)'), ('F', 'Fail (0-39)')], editable=False, max_length=3)),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], editable=False, max_length=10)),
                ('exam_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.subject')),
            ],
            options={
                'ordering': ['-exam_date'],
                'indexes': [models.Index(fields=['student', 'subject'], name='api_result_student_5b0ab2_idx'), models.Index(fields=['status'], name='api_result_status_7a9a83_idx'), models.Index(fields=['exam_date'], name='api_result_exam_da_d61fed_idx')],
                'unique_together': {('student', 'subject', 'exam_date')},
            },
        ),
    ]
